### PR TITLE
Bugfix connection

### PR DESCRIPTION
**Pull request by malotor**
Allow event listenners work with all connections not only "default"

### CODE REVIEW

**Comment by v-bartusevicius** [comment]
Any news on this?

**Comment by malotor** [comment]
Hi v-bartusevicius  the changes done in this branch works for me. Hope it helps you :)

**Comment by v-bartusevicius** [comment]
Just looked the source - still `connection="default"`, could you please explain how it works to you?

**Comment by malotor** [comment]
Yes, if you set 'connection="default"' the listenner only works with this concrete connection. If you remove this, it will listen all connections.

**Pull request closed without merging**
