### PR TITLE
skip revision table creation if already exists

### PR DESCRIPTION
**Pull request by devilcius**
In case the `revision` table name is modified, it prevents a `Doctrine\DBAL\Schema\SchemaException`:

>The table with name 'database.customized_revision' already exists.

### CODE REVIEW

**Comment by andrewtch** [comment]
Thanks for the PR, but under what circumstances do you modify revision table?

**Comment by devilcius** [comment]
For naming consistency in my db schema:
*config.yml*:

    simple_things_entity_audit:
        ...
        revision_table_name: customized_revision

**Comment by andrewtch** [comment]
So, if you use custom revision table name, you have an error saying that this table can not be created?

**Comment by devilcius** [comment]
That's it. A `Doctrine\DBAL\Schema\SchemaException`:

>The table with name 'database.customized_revision' already exists.

**Comment by smoench** [comment]
@devilcius If this is still relevant, please feel free to open a new clean PR

**Pull request closed without merging**
