### PR TITLE
Fix auditing of entities with fields that require sql conversion

### LINKED ISSUE #196: Fields that require SQL conversion to convert to database value not converted when saving to the audit table.
When an audited entity contains a field with a custom mapping type that requires calling a SQL function to convert to a value suitable for the database column, EntityAudit is not performing the SQL conversion when saving the field value to the audit table. The original, unconverted value is stored instead.

### PR DESCRIPTION
**Pull request by jamescdavis**
Fix #196

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by bendavies** [comment]
@jamescdavis can you rebase this please?

**Comment by jamescdavis** [comment]
rebased

**Comment by bendavies** [comment]
thanks @jamescdavis !

**Pull request merged**
