### PR TITLE
Support auditing of entities identified through foreign entities

### LINKED ISSUE #194: Auditing of entities identified through foreign entities does not work.
As of 2.1, Doctrine supports [identity though foreign entities](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/tutorials/composite-primary-keys.html#identity-through-foreign-entities). EntityAudit cannot currently add revisions for entities whose identifier field is another entity. Consider [this example of a simple derived entity](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/tutorials/composite-primary-keys.html#use-case-2-simple-derived-identity):

``` php
/**
 * @Entity
 */
class User
{
    /** @Id @Column(type="integer") @GeneratedValue */
    private $id;
}

/**
 * @Entity
 */
class Address
{
    /** @Id @OneToOne(targetEntity="User") */
    private $user;
}
```

User can be audited, but Address cannot because it is identified through User.

### PR DESCRIPTION
**Pull request by jamescdavis**
fix #194

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by bendavies** [comment]
hi @jamescdavis, thanks! can you rebase this please?

**Comment by jamescdavis** [comment]
rebased

**Comment by bendavies** [comment]
Hi @jamescdavis 
Thanks, but there looks to be further issues that need fixing here.
If you add this to the bottom of your test:
```php
        $auditReader = $this->auditManager->createAuditReader($this->em);

        $auditReader->find(get_class($user), $user->getId(), 1);

        $address = $auditReader->find(get_class($address), $address->getUser()->getId(), 2);
        $this->assertEquals($address->getUser(), $user);
```

you'll see it fails, so there are bugs in the audit reader somewhere.

Can you take a look?

**Comment by jamescdavis** [comment]
Hey, @bendavies. That test was failing because my fixtures don't have any getters. :) I was just testing successful persistence, but you're right that I should test the reader too. I'll update the fixtures and add an assert. Also, in the code above, I'm assuming you meant to assign the user found with the audit reader back into $user before the assert?

**Comment by jamescdavis** [comment]
Rebased and added audit reader checks, now failing all builds on travis, but all tests passing for me locally. Going to try to figure out why...

**Comment by jamescdavis** [comment]
Somebody had turned off E_NOTICE on our dev server! I've updated the audit reader and now my tests are passing. Should be good to go now.

**Comment by DavidBadura** [comment]
Sorry for the late response. I'm trying to push the project forward. Can you please rebase your PR? I will merge it immediately if the tests are successful.

**Comment by jamescdavis** [comment]
@DavidBadura looks like you're having build problems with COMPOSER_FLAGS="--prefer-lowest" as well. It seems that composer is taking exceptionally long to calculate the dependencies and Travis is timing out. In my local dev env, composer only takes a few seconds to calculate dependencies, even when using --prefer-lowest. Not sure why it's so slow on Travis.

**Comment by jamescdavis** [comment]
Also, on a related note, even if Travis would let the composer update finish, almost every test fails because composer.json says the minimum required doctrine/orm version is 2.4, and commit 49f9454ca0c49a740a048c4b1fc8a6423cf3f977 makes 2.5 a requirement.

**Comment by DavidBadura** [comment]
Oh, thank you! I have already asked myself why the build fails. I will fix it! Thanks!

**Pull request merged**
