### PR TITLE
Rename global_ignore_columns to global_ignore_properties

### PR DESCRIPTION
**Pull request by peschee**
When reading the documentation

```yml
# If you need to exclude some entity properties from triggering a revision use:

simple_things_entity_audit:
    global_ignore_columns:
        - created_at
        - updated_at
```

one would assume that you need to specify the name of your actual database table columns in order to ignore changes for them. However, the `LogRevisionsListener` watches for changes on entity properties (property names) not on the database field names (see #135).

The proposed change is to make the configuration as such:

```yml
simple_things_entity_audit:
    global_ignore_properties:
        - createdAt
        - updatedAt
```

`global_ignore_columns` should rather be called `global_ignore_properties`. I've also updated the tests to reflect this. Since camelCased properties were never tested so the tests never failed.

**Important**: this is a BC-change, so a new version should be tagged accordingly. Or even better: if someone knows a way to support both, but mark the `global_ignore_columns` option as deprecated, feel free to chip in.

### CODE REVIEW

**Comment by tolry** [comment]
@peschee I agree, your naming is definitely less error prone.

Keeping this BC compat would be great, has anyone some spare time and the appropriate knowledge to assist @peschee with this?

/cc @smoench @DavidBadura

**Comment by bendavies** [comment]
This seems great, and as previously discussed BC is not a concern at the moment @tolry.
@peschee can you please rebase this?

**Comment by peschee** [comment]
@bendavies I rebased my change on `master`, but I guess now this is wrong? Too many commits it seems :) What's the best way to get rid of those before my change?

**Comment by bendavies** [comment]
@peschee i'm not sure what happened there!

i would have done something like:
```
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
$ git checkout global_ignore_columns_case
$ git rebase master
```

**Comment by peschee** [comment]
@bendavies That's what I did, but without the force push. I guess easiest is to cherry pick my changes into a new branch and make a new PR?

**Comment by bendavies** [comment]
@peschee try the force push! otherwise feel free to make a new PR

**Comment by peschee** [comment]
I have made a new PR #213.

**Pull request closed without merging**
