### PR TITLE
enitity metadata, revision metadata, revision finding

### LINKED ISSUE #37: Allow tagging of version
It would be nice to have a particular version tagged similar to git. It doesn't have to be unique.

Then add revertByTag() method to repository class

### PR DESCRIPTION
**Pull request by andrewtch**
Meta WIP. Now you can attach meta data to revision and entities and query revisions by metadata (array or raw query). Can someone check if it runs fine in symfony context?

Closes #37

### CODE REVIEW

**Comment by andrewtch** [comment]
@DavidBadura , I've rebased it, but haven't checked in symfony context. Can you take a look on the code?

**Comment by andrewtch** [comment]
Now there's a test if bundle can load it's configuration in Symfony context correctly, please review.

**Comment by andrewtch** [comment]
Closing as obsolete

**Comment by irmela** [comment]
Hi 👋 
I was wondering why this PR was closed? Is it already implemented in another way?

**Comment by andrewtch** [comment]
It just did not make it to release )

**Pull request closed without merging**
