### PR TITLE
Updated LogRevisionsListener.php

### PR DESCRIPTION
**Pull request by dlegatt**
Removed sequence name generation to fix error with SqlServer platform

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | no
| Fixed tickets | #230

### CODE REVIEW

**Comment by DavidBadura** [comment]
Thanks! I am wondering why only one environment (postgres + 5.6) fails :-/ I have restarted the tests...

**Comment by DavidBadura** [comment]
I think the low dependencies are the cause

**Comment by DavidBadura** [comment]
Can you increase the dbal requirements on patch level until the tests are green?

from `~2.5` to:

* `^2.5.1`
* `^2.5.2`
* ...

I think dbal has solved it, but I don't know in which version.

--------

You need only change the composer.json, commit and push it. Everything else happens automatically.

**Comment by smoench** [comment]
👎 #230 is an issue with dbal and sql server.
I think pgsql (in older versions) is requiring a sequence name for last inserted id.

IMHO: if a platform is supporting sequence names they should be used.

**Comment by DavidBadura** [comment]
Ah, now I understand. Sorry @dlegatt but it's an error in dbal (https://github.com/doctrine/dbal/issues/2467). We should keep sequence support for other platforms.

**Pull request closed without merging**
