### PR TITLE
Adds support for inherited associations on single-table-inheritance sub-classes

### PR DESCRIPTION
**Pull request by davidomelettes**
Addresses Issue #156, where AuditReader::find() fails to load entities belonging to a sub-class of a target entity using single-table-inheritance.

### CODE REVIEW

**Comment by DavidBadura** [comment]
Hey, can you add a test for it? thx :)

**Comment by davidomelettes** [comment]
@DavidBadura Test added.

**Comment by tolry** [comment]
lgtm :+1:

**Comment by DavidBadura** [comment]
:+1:

**Comment by DavidBadura** [comment]
Thank you!

**Pull request merged**
