### PR TITLE
Allow to work when the associations don't have the revision

### LINKED ISSUE #157: OneToOne associations not supported when owning side does not exist
Consider the following entities:

```
class Human
{
    /**
     * @ORM\OneToOne(targetEntity="Robot", mappedBy="human")
     */
    property $robot;
}

class Robot
{
    /**
     * @ORM\OneToOne(targetEntity="Human", inversedBy="robot")
     */
    property $human;
}
```

If you persist a Human without a Robot, attempting to load an instance of that Human from AuditReader::find() will fail, as it attempts to find a Robot with the corresponding `human_id`. It currently seems to assume that both sides of a OneToOne association must exist. This is the workaround I am using:

```
try {
    $value = $this->find($targetClass->name, $pk, $revision, array('threatDeletionsAsExceptions' => true));
} catch (DeletedException $e) {
    $value = null;
} catch (NoRevisionFoundException $e) {
    $value = null;
}
```

### PR DESCRIPTION
**Pull request by edwines**
Fix #157

### CODE REVIEW

**Comment by bendavies** [comment]
@edwines can't you please include a test case for this.

thanks!

**Comment by bendavies** [comment]
@edwines i can't replicate this issue, using a OneToOne like in the issue described.
Can you confirm if this is still any issue?

**Comment by edwines** [comment]
Yes, I pull the most recent version of the EntityAudit and this issue still exists.

Steps to reproduce:

1. Create two Tables like Human and Robot (see #157)
2. Configure the entities in EntityAudit:
```yamel
simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\Human
        - AppBundle\Entity\Robot
```
3. Create a Human with a null Robot
4. Call findRevisionHistory and a NoRevisionFoundException will be thrown

**Comment by nicolasricci** [comment]
I can confirm this is still an ongoing issue and this PR fixes this. @bendavies can this be reviewed for merge?

**Comment by Soullivaneuh** [comment]
This way is not right IMO because the associated property will be null like, it does not exists at all.

But this is wrong, the related property exists, just without revision.

We should fallback to the `EntityManager::find` method instead.

See https://github.com/simplethings/EntityAudit/pull/227

**Comment by DavidBadura** [comment]
Closing in favor of #227

**Pull request closed without merging**
