### PR TITLE
Change LogRevisionsListener methods to protected

### PR DESCRIPTION
**Pull request by rvanlaarhoven**
Changed all private methods in `LogRevisionsListener` to protected in order to be able to extend the listener without having to override everything.

### CODE REVIEW

**Comment by OskarStark** [comment]
seem reasonable to me

**Comment by DavidBadura** [comment]
change everything to protected is dangerous. its more difficult to changes something without bc-breaks for us. what do you want override?

**Comment by smoench** [comment]
:-1:

**Comment by tolry** [comment]
As @DavidBadura said, making properties/methods protected makes that part of your code effectively public API when dealing with libraries that are extended by developers. Making it necessary to consider BC for every possible refactoring in this code.

@rvanlaarhoven it would be really helpful to know, what you intend to extend/modify. Mostly extension by composition is less error prone, than by inheritance. Probably events might be a better solution here than extending the class.

**Comment by rvanlaarhoven** [comment]
Actually, we decided to stick with our old solution (Gedmo Loggable) for now, until we have some more time to refactor. so this PR is not directly necessary.

To clarify what I intended to do is override `saveRevisionEntityData`, to;
- Add another column to the audit table with extra log data.
- We're using versioning on a nested entity structure, with publish functionality. Not every change needed a new audit row, so when a log was already created and the version wasn't published yet, I needed to execute an UPDATE instead of an INSERT.

**Comment by tolry** [comment]
@rvanlaarhoven thx for clarification, OK if I close this PR for now? If this gets relevant for you later, I would like to work on a different solution (e.g. events, see above) for this. Providing special hooks for extending the existing functionality.

**Comment by DavidBadura** [comment]
ref #83 ??

**Comment by rvanlaarhoven** [comment]
@tolry Thanks!

**Pull request closed without merging**
