### PR TITLE
Update CreateSchemaListener.php

### PR DESCRIPTION
**Pull request by TheRatG**
Optimize queries

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
EntityAudit still supports php 5.3.x (at least, according to composer.json). Could you use the old array syntax here? Otherwise :+1: from me too.

**Comment by smoench** [comment]
but there is another failure:

```
Doctrine\ORM\Tools\ToolsException: Schema-Tool failed with Error 'An exception occurred while executing 'CREATE INDEX revision_idx ON UserAudit_audit (rev)':
SQLSTATE[HY000]: General error: 1 index revision_idx already exists' while executing DDL: CREATE INDEX revision_idx ON UserAudit_audit (rev)
```

**Comment by TheRatG** [comment]
Ok.

**Comment by TheRatG** [comment]
rev_idx fixed


pdo_sqlite gives *SQLSTATE[HY000]: General error: 1 index rev_idx already exists*
```
CREATE INDEX rev_idx ON OwnerEntity_audit (rev);
CREATE INDEX rev_idx ON OwnedEntity1_audit (rev);
```

**Comment by dmkuznetsov** [comment]
Nice! :+1:

**Comment by whyte624** [comment]
:+1:

**Pull request merged**
