### PR TITLE
Update attributes of entity in one query and fixed finding of column in association mappings

### PR DESCRIPTION
**Pull request by N4IR0**
This changes will fix #180.
I have also fixed the code block of finding a column in association mappings, because the variables were never used in this method.

### CODE REVIEW

**Comment by W0rma** [comment]
Any chance to get this PR merged @bendavies @DavidBadura @tolry ? Sounds useful to me.

**Comment by bendavies** [comment]
I'll take a look at this soon. Really need to make sure we have tests covering this.

**Comment by DavidBadura** [comment]
Is it a replacement of #180? Can you finished it (rebase / tests)? Thanks!

**Comment by DavidBadura** [comment]
replaced by #253

**Pull request closed without merging**
