### PR TITLE
result caching

### PR DESCRIPTION
**Pull request by andrewtch**
@DavidBadura , please take a look on a cache layer (do not merge yet)

### CODE REVIEW

**Comment by andrewtch** [comment]
@DanielBadura , I've fixed the small issues and rebased to latest master.

**Comment by DavidBadura** [comment]
a small documentation would be nice :)

**Comment by andrewtch** [comment]
As for doc - please check your e-mail; we have hell lot of points to document )

**Comment by andrewtch** [comment]
@DavidBadura , rebased, documented and checked against newest fixes in master. Again, please check your e-mail so we can think about future development, thanks!

**Comment by tolry** [comment]
Is this still relevant/current? Needs another rebase.

**Comment by andrewtch** [comment]
Closing as absolute

**Comment by OskarStark** [comment]
you mean "obsolete" i think

**Pull request closed without merging**
