### PR TITLE
Use QueryBuilder in postFlush and update entity changes with one query

### PR DESCRIPTION
**Pull request by smoench**
| Q             | A
| ------------- | ---
| Bug fix?      | probably
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Has tests?    | yes
| Fixed tickets | #201

### CODE REVIEW

**Comment by DavidBadura** [comment]
Can we somehow test it? So if really only one query is fired?

Since it is not a "function" in itself, it is not bad to have no test for it. But if it's simple, it would be cool.

**Comment by DavidBadura** [comment]
Thank you!

**Comment by eduardoweiland** [comment]
Could this change be merged into the 1.0 branch too? Currently this change is only available in branch master.

**Comment by webostin** [comment]
Is there any reason why these changes have not been released? (it's only in master branch)

**Comment by VincentLanglet** [comment]
> Is there any reason why these changes have not been released? (it's only in master branch)

The repository owner changed, maybe 1-2 year ago.

When we got this repository, since we had no clue about what was done/needed to be done on the master branch, we created a new branch for the next major: 2.x.

If this changes are Backward compatible, feel free to open a PR on 1.x.

**Pull request merged**
