### PR TITLE
Fixes for symfony 3

### LINKED ISSUE #165: Fix deprecation for security.context
Could you, please, fix this error:
> The "security.context" service is deprecated since Symfony 2.6 and will be removed in 3.0.

which is in
simplethings/entity-audit-bundle/src/SimpleThings/EntityAudit/Resources/config/current_username.xml:15

### PR DESCRIPTION
**Pull request by npoa-cm**
fix #165

### CODE REVIEW

**Comment by tolry** [comment]
:+1:

**Comment by DavidBadura** [comment]
splitting the component was made in symfony 2.6. if we change that we need to elevate the version.

**Comment by smoench** [comment]
@npoa-cm please open a clean PR without the merge commit and increase the conflict constraint `symfony/framework-bundle` in `composer.json` to `<2.7`

**Comment by npoa-cm** [comment]
Done

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
anymore objections @smoench - otherwise I would merge this

**Comment by smoench** [comment]
the `require-dev` entry of `symfony/framework-bundle` could be changed to `~2.7|~3.0`

**Comment by npoa-cm** [comment]
Done

**Comment by DavidBadura** [comment]
:+1:

**Comment by smoench** [comment]
Thank you @npoa-cm

**Pull request merged**
